; Disassembled text of ../assembler/a.out
; Generated by disasm (c) Victor Baldin, 2023

in 
pop rax
in 
pop rbx
in 
pop rcx
push rbx
push rbx
mult 
push rax
push rcx
mult 
push 4.000000
mult 
sub 
out 
hlt 
